### ISSUE TITLE
Support for ODE based models

### ISSUE THREAD

**Issue by mattgra** [CiaranWelsh/PyCoTools#10]
Hi there,

I'm currently trying to run a time-course simulation with a COPASI model based on ODEs (not reactions). However, I'm always getting an error
"InputError: type should be either fixed or assignment. ODE not supported as Reactions can be used."

Is there any possibility to do this with the current PyCoTools release? Or is an implementation of time course simulations with ODE models planned for the future?

Thanks.

**Comment by CiaranWelsh** [comment]
Hello Matt,

Unfortunately no, I haven't developed pycotools for use with directly solving ODE's from the global variables tab. Is there a reason why you have to input ODE's directly? If so, perhaps scipy or matlab would be a more suitable choice of software? If not, to get the full benefit of COPASI (and pycotools), I'd recommend switching to inputting reactions with a rate law.

Sorry, but I don't plan on implementing support for this feature anytime soon - mostly due to time constraints. I'll certainly make the error message a bit clearer however - thanks for bringing this up, 

all the best, 

Ciaran
