### ISSUE TITLE
Python 3.7 or 3.8 support?

### ISSUE THREAD

**Issue by paulstapor** [CiaranWelsh/PyCoTools#14]
Hi,

I was intending to use PyCoTools for a couple of simulations. However, the last supported Python version seems to be 3.6...
So, I was wondering: Are there big changes to be made to have PyCoTools running in 3.7, or where's the problem exactly?
Actually, I just need a wrapper around CopasiSE, whihc adapts some of the Copasi tasks (just time courses)... What would be the best qay to achieve this?

Best,
Paul

**Comment by CiaranWelsh** [comment]
Hello, 

Please check out the PyCoTools3 repository here: https://github.com/CiaranWelsh/pycotools3. 

The problem was that one of pycotools dependencies (tellurium) only supported python 3.6 at the time. They now support Python3.7 but not 3.8, so Pycotools3 should work on Python3.7. 

Please try `pip install pycotools3`

**Comment by paulstapor** [comment]
ah, okay! Thanks and sorry for asking this question in the wrong repository!
